### ISSUE TITLE
ocropy model

### ISSUE THREAD

**Issue by wanghaisheng** [isaomatsunami/clstm-Japanese#4]
do you use ocropy to train a model?

**Comment by isaomatsunami** [comment]
Yes, training data is made with codes in ocropy.
Making line-strip data out of scanned pages is another hard problem. You have any idea?
I just tested whether clstm can deal with over-3000 classification. Clstm can do it brilliantly well.

**Comment by wanghaisheng** [comment]
at first i want to train a chinese model by load your clstm model ,but it seems broken and could not load . right now i was using ocrolinegen to get the trainning data for both library to run first round of my model trainning process
